language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: pjI0obm+RiHn6eHqCTHu/t6ybt7cI9Li/FMcEqgyeZvtvcOURoRiN61Whoje9tEkUCV9tU2AbUwZwqmEDoqIFqQi6l4JkgRyF/Rit2lLqbuP/TSOn/iaOtLg86iGXjPSocuYM8DIekCQXRakfAI2VFyTSD9CyPcLg04HD19CdUfeF7bhdTJuAGvrsmMWXvJ52QKdbxZK40sfQikhR/tpmYdI5hA0yMi7jTPrSJEhDDT4aoD+LqZAK9KWFKQtXD+zRzFkQA0hykGqzyIufYRD/oLQ4qgwMdWCtSvdnaEV+ILkyO10RwuB8zG1jLSx29Ae9UUWxoP6ELu02zADBJvul40FV7LDSHR2M1aX/3fNWZ7SpWammo0Wb+8RscNNXBLEIu0EcT1NGGq5ab74psgmDkghVvPCPheuLcsaKwFPqD9LoMRjKEJIMYQfGkVXOXtjUx/r7H+r0OO23JqN8loauaoFiYj0z541qY2OYgE8BBUjAvKSJ2ClGJom8dc0kzgLvzwPC7+QU2W5bPcAaLBMp+zhe1FrkT6bEG5BptTanHyhlGZDUv3Xbl/GXixIY6ll7g+YlHEgQETUwM1lnbFi1TJPfxL1AgicMt9Z15s0yT2/w7iLkiD6m/XJoDWH+SeG/WD44W95FPbYUpZ+Ry3TS/UBiswkHEGAh+1ejcubmj4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
  - bundle/cache
before_install:
- rvm install 2.1
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
